version: '3.8'

services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile  # your existing Dockerfile for Streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501

  flask_api:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    volumes:
      - .:/app
